spring:
  h2:
    console:
      path: /h2_console
      enabled: true
  datasource:
    url: jdbc:h2:file:~/menu_dev
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show-sql: true
        format_sql: true

server:
  port: 8081
  servlet:
    context-path: /api

