spring:
  profiles :
    active : prod
  h2:
    console: enabled=true
    path: /h2_console
  datasource:
    url: jdbc:h2:mem:~/menu_dev
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8081
  servlet:
    context-path: /api